name: CEEI jobs release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'
    - name: Set up Python 
      uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        # sudo apt-get update
        # sudo apt-get install curl gdal-bin libgdal-dev 
        # python3 -m pip install --upgrade pip
        # python3 -m pip install -r requirements
        echo "Testing release not needed"
    - name: Analysing the code with pylint
      run: |
        echo "Skipping pylint for now"
        # pylint africa.py
    - name: Create Release
      uses: actions/create-release@latest
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          New ceei version
        draft: false
        prerelease: false
    - name: Publish release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ceei_jobs.csv
